version: '3.9'

services:
  frontend:
    build: .
    container_name: github-actions-nextjs
    ports:
      - "3000:3000"
    networks:
      - shopnetwork

networks:
  shopnetwork:
    external: true
