version: '3.8'

services:
  frontend:
    build: .
    container_name: github-actions-nextjs
    ports:
      - "3000:3000"
    networks:
      - shopnetwork

networks:
  network1:
    name: shopnetwork
    external: true
