version: '3.4'

services:
  frontend:
    build:
      context: .
      network: shopnetwork
    container_name: github-actions-nextjs
    ports:
      - "3000:3000"
    networks:
      - shopnetwork

networks:
  shopnetwork:
    name: shopnetwork
    external: true